name: Regression and Unit Post-Validation on Linux ARM64

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    uses: ./.github/workflows/regression.yml@e72f0bba8bd8e7d28b6e285bfa6d54a1a7547e8a